import type { Metadata } from "next";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import { geistSans, geistMono } from "../fonts/fonts";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}  antialiased`}>
        <Header />
        <main className="container min-h-screen mx-auto p-4">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
